### PR TITLE
Quiz

### PR DESCRIPTION
**Pull request by guthb**

### CODE REVIEW

**Comment by gregkorte** [comment]
Nice work on your quiz, Brad. There are a few things to check out. First, on your `quiz.js` you are passing `CarLot` into your `populatePage` function. The way an IIFE functions should allow you to call your `activateEvents` function without having to pass the IIFE around. Second, be careful of trailing whitespace. It can cause merge conflicts. If you want a tool to check your whitespace, come see me, and we'll get it installed to your sublime. Last, you have a nice commit history, but it's not crystal clear what you were doing between changes. A little more verbose on your commits will help others who will eventually look at your code. So, just fix the IIFE, and you are good to go. :+1:

**Comment by guthb** [comment]
I believe i have my error corrected, review when you can.

**Comment by gregkorte** [comment]
Nice work, Brad. I saw something I missed the first time around. The instructions state that you should have rows of three cards inside the container with Bootstrap styling. This should be accomplished in your card builder. Let me know if you have  any questions.

**Comment by guthb** [comment]
Greg,

I could use some guidance/aid as i was unsure of my bootstrap but was instructed to submit my quiz regardless.

I will seek you out this evening.

**Comment by guthb** [comment]
updated with three cards in two rows with separation

**Comment by gregkorte** [comment]
Hey Brad. Getting closer! So now you just need a row for every three cards. Think about a conditional statement that will  insert a row every three cards. If you're having trouble with it after today, we'll walk through it so you can get this quiz out of the way. :)

**Comment by gregkorte** [comment]
Looks good! :+1:

**Pull request merged**
